const REGULAR_ICON_SIZE = 24;
const PRIMARY_ICON_SIZE = 28;
const ITEM_PADDING = 16;
const TAB_BAR_SIZE = REGULAR_ICON_SIZE + (ITEM_PADDING * 2);
const SELECT_INDICATOR_POSITION = ITEM_PADDING + (REGULAR_ICON_SIZE / 2) - 1;
const TAB_BAR_PADDING_BOTTOM = 16;
const ALL_TAB_BAR_HEIGHT = TAB_BAR_SIZE + TAB_BAR_PADDING_BOTTOM;

export const TabBarConstants = {
  REGULAR_ICON_SIZE,
  PRIMARY_ICON_SIZE,
  ITEM_PADDING,
  TAB_BAR_SIZE,
  SELECT_INDICATOR_POSITION,
  TAB_BAR_PADDING_BOTTOM,
  ALL_TAB_BAR_HEIGHT,
};